### ISSUE TITLE
请问这是什么原因造成的，之前的可以运行，现在的会出现这个问题

### ISSUE THREAD

**Issue by sizhandailiawa** [line/lighthouse#26]
AttributeError: 'CGDETRPredictor' object has no attribute 'video_path'

**Comment by awkrail** [comment]
@sizhandailiawa 
Thank you for your feedback. Let me investigate it.

**Comment by awkrail** [comment]
@sizhandailiawa 
Did you run `python api_example/demo.py` command? I cannot reproduce the issue in my environment. Could you give some codes to reproduce it or detailed error logs?

In addition, this repo is actively updated. Hence, could you re-run the following command again?
```
pip install 'git+https://github.com/line/lighthouse.git'
python api_example/demo.py
```

**Comment by awkrail** [comment]
Unfortunately, I couldn't reproduce the result. But, I guess that this error occurs because you use the old version of Lighthouse. The current CGDETRPredictor set video_path to be None when initializing the instance.

Hence, to remove this error, I recommend you to uninstall and re-install the latest version of Lighthouse. If this solves the problem, please let me know.
