### ISSUE TITLE
Will you consider adding audio features?

### ISSUE THREAD

**Issue by ffiioonnaa** [line/lighthouse#28]
Hi，thanks for your works！I was wondering if you would consider adding audio features?

**Comment by awkrail** [comment]
@ffiioonnaa Hi, I implemented training, inference API, and gradio demo. As reported in [reproduced_results.md](https://github.com/line/lighthouse/blob/main/markdown/reproduced_results.md), adding audio features slightly improves the model's performance (but not always true). Because the difference is slight, we cannot observe the positive difference of the predicted results between CLIP+Slowfast and CLIP+Slowfast+PANNs (audio).
