### ISSUE TITLE
In the inference stage, is it possible to support other frame rates for frame sampling? 

### ISSUE THREAD

**Issue by ffiioonnaa** [line/lighthouse#38]
Hi, I would like to know if it is possible to modify the framerate of slowfast and clip in the inference stage. 
1. The input of Slowfast is 32fps, can I use less frame rate such as 16, how do I need to modify the code? 
2. If the clip_len is changed to a different value, how to change Slowfast?
Thanks!

**Comment by awkrail** [comment]
> The input of Slowfast is 32fps, can I use less frame rate such as 16, how do I need to modify the code?

No because the CLIP+Slowfast models are trained on 32fps videos.
If you want to change them to 16fps, please read this part. However, I am not sure what's happen if you change 32 to 16 fps.
https://github.com/line/lighthouse/blob/main/lighthouse/frame_loaders/slowfast_loader.py

> If the clip_len is changed to a different value, how to change Slowfast?

clip_len should be same (clip_len = 2, 0.5 fps) because the models are trained on this parameter.

**Comment by awkrail** [comment]
If you have further questions, please re-open the issue again.
